runtime: php74

runtime_config:
  document_root: public

env_variables:
  APP_LOG: errorlog
  APP_KEY: base64:5B97eIefOYQYFXKPARGfLB1J+GlOG5jUUGAEHXHM/kQ=
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  DB_DATABASE: laravel
  DB_USERNAME: laravel
  DB_PASSWORD: 's9B2l43MF06sfw121230'
  DB_SOCKET: "/cloudsql/chitano-ycvpxv:us-west1:laravel-app"
